### ISSUE TITLE
Correct AIM course schedule

### ISSUE THREAD

**Issue by sassteve** [BYU-ODH/byu-humanities-department#14]
Need to follow-up to see if this is still an issue.
http://ane.byu.edu/

**Comment by WorldsEndless** [comment]
The data is appearing again. Some styling corrections are needed to the style.css to make these look right. e.g: 

http://linguistics.byu.edu/blog/program/linguistics-ba-2/
http://linguistics.byu.edu/blog/program/english-language-ba-2/
http://linguistics.byu.edu/blog/program/linguistics-minor-3/

**Comment by sassteve** [comment]
The linguistic pages shouldn't be much of an issue, though the shortcodes on the ane.byu.edu for all of the programs aren't' working still.
