### ISSUE TITLE
Give WP Admins checkboxes for 1. displaying calendar widget, 2. displaying quick links, 3. making carousel auto-rotate

### ISSUE THREAD

**Issue by DerekMoss95** [BYU-ODH/byu-humanities-department#29]
Create three custom field groups on dashboard and export in php to acf_byuh.php file to give any department site the 3 different things listed: 
1. Display the calendar widget
2. Display the quick links widget
3. Turn on the auto-rotate feature for the carousel

**Comment by DerekMoss95** [comment]
This project is completed in the sense that the different checkboxes have been added and are already in the acf_byuh.php file, but until it is committed and pushed to the department code, it isn't truly finished.

**Comment by WorldsEndless** [comment]
Can you please provide brief instructions and URL for testing so I 
can see how it looks, and then I can accept a pull request

**Comment by DerekMoss95** [comment]
So I wrote the different checkbox custom fields and you can test it on humstaging.byu.edu/spanport. The radio buttons work already so when you put false for show calendar or false for show quick links, it will hide whatever you choose if selected. Once Aaron has finished the auto-rotate functionality, we will be ready for the pull request I believe because I made a third one to turn auto-rotate on or off, but I can't make that part actually functional until we have Aaron's part. I know it will work, but we need that functionality to see if it truly works.

**Comment by DerekMoss95** [comment]
http://humstaging.byu.edu/spanport/wp-admin/post.php?post=11&action=edit to change show calendar/quick links to true or false
