### ISSUE TITLE
Main nav dropdowns for wide nav areas don't work on smaller screens

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#3]
![menu-cutoff](https://cloud.githubusercontent.com/assets/5042778/18754627/90b4e188-80a6-11e6-985c-5d12bf343593.jpg)

**Comment by sassteve** [comment]
@WorldsEndless We can decrease the size of the navbar for a certain screen sizes. If possible, then I'd like to put an if statement in the code saying that if it's the first item on the submenu, and it's a dropdown, then have it display `left:0`

**Comment by sassteve** [comment]
Couldn't get the `left:0` to work for the far left dropdown for the submenu, though was able to adjust the size of the block in the submenu to work for any screen size. It is included in the branch main-navbar-dropdown
