### ISSUE TITLE
Live sites need to be upgraded to latest wordpress

### ISSUE THREAD

**Issue by aaroncowley** [BYU-ODH/byu-humanities-department#35]
All live sites are behind on wordpress version.  Sites will need to be updated so they have the latest security patches and compatibility with plugins.

**Comment by WorldsEndless** [comment]
Ashley, if you could take care of this that would be great. There is probably no issue, but as always, check in staging first if possible.

**Comment by sassteve** [comment]
I can't get into humstaging nihongo, sliva, or hum50. Otherwise the other humstaging sites are already up-to-date Wordpress wise.

**Comment by WorldsEndless** [comment]
Excellent work. Those three sites are special-interest sites with 
dedicated groups working on them besides our team, hence the 
reason they can't be accessed.

**Comment by aaroncowley** [comment]
linguistics, germruss, french italian, asiane, and spanport are still behind on wordpress update, just want to rule this out as a potential cause for the asiane homepage issue

**Comment by sassteve** [comment]
Let's update all of them. The update on humstaging all went well.
