### ISSUE TITLE
Carousel Autopopulation

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#4]
The front-page article carousel should automatically populate from the college, when the college posts articles with affiliation matching the department.

**Comment by aaroncowley** [comment]
ready for integration

main site needs:
- slugs changed for post categories with corresponding sites using carousel code
- posts to be unrestricted in press permit core plugin 
- active rest api endpoints

department sites need:
- updated code utilizing rest api
- byuh tools page to have correct site slug
- default image to be uploaded into theme files (jfsbcourtyard.jpg)

**Comment by aaroncowley** [comment]
![jfsbcourtyard](https://user-images.githubusercontent.com/7765456/27409113-04323f6c-569d-11e7-8b4c-18a263b888e4.jpg)

**Comment by WorldsEndless** [comment]
This appears to be bogging down the server. We'll have to re-evaluate how the loops is running.
