### ISSUE TITLE
Student Faculty needs to be an option

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#54]
In addition to making it possible to see student faculty (something needed soon!), we have so many categories now, we need it to be a dropdown instead of a line of options. 

![student_fac](https://user-images.githubusercontent.com/5042778/30556753-2c72f4be-9c69-11e7-8e57-855f99ed679d.png)

**Comment by aaroncowley** [comment]
both the dropdown and the sorting now work submitting merge request
