### ISSUE TITLE
Add "Calendar" front-page option like humanities.byu.edu

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#6]
Special request including Ling. 

Make checkbox to select whether it is shown or not as well.

https://github.com/BYU-ODH/byu-humanities-theme/blob/master/page-templates/home.php#L83

![calendar](https://cloud.githubusercontent.com/assets/5042778/19133396/3ed3e368-8b15-11e6-9e95-6ea2effe3824.jpg)

**Comment by DerekMoss95** [comment]
Created checkbox and it works properly with my code written in home.php to recognize whether calendar should be shown or not on spanport. Need to export as php acf and save to all department sites.

**Comment by DerekMoss95** [comment]
Exported the custom field acf succesfully and saved within the acf_byuh.php file. Functional radio button to show or hide the calendar widget on the front page.
