### ISSUE TITLE
Carousel Styling Needs Fix Across all Departments

### ISSUE THREAD

**Issue by DerekMoss95** [BYU-ODH/byu-humanities-department#63]
The carousel placement isn't determined correctly. If you remove those little boxes where the image is, the carousel moves up into the image. We should be able to have the carousel stay where it is always and not be thrown off by these boxes.
![stylingissuecarousel](https://user-images.githubusercontent.com/25596232/33638840-8119fcb0-d9e5-11e7-83a6-648e7f41fc25.jpg)

**Comment by sassteve** [comment]
Created a branch and tested it out on humstaging.byu.edu/english

**Comment by sassteve** [comment]
Submitted a final request, about done.
