### ISSUE TITLE
Mobile Version of Department Sites need help

### ISSUE THREAD

**Issue by DerekMoss95** [BYU-ODH/byu-humanities-department#64]
![image](https://user-images.githubusercontent.com/25596232/33680651-8c1ae120-da7f-11e7-8042-9c193c346d86.png)
The mobile version of department sites need help with styling. As we can see here, the menus go way too far down and probably need to be placed into accordions. The carousel and little front boxes on the home pages are a little out of wack as well, as we can see here:
![image](https://user-images.githubusercontent.com/25596232/33680752-d36f5538-da7f-11e7-8aa4-bbe83d69718e.png)

**Comment by sassteve** [comment]
We'll create a project later down the road to rewrite the entire theme.

**Comment by sassteve** [comment]
JK We're going to fix the bug this semester and then redesign the theme later

**Comment by sassteve** [comment]
In home.php, put the footer in the `<div id=page >` and it allows for the movement of the footer when the `mobile-menu` is activated, also puts the footer in front of the menu
