### ISSUE TITLE
Front-page calendar widget

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#66]
Some departments want the option for a front-page calendar widget like the college has:

http://humanities.byu.edu

![calendarwidget](https://user-images.githubusercontent.com/5042778/33722829-47399a52-db28-11e7-81b2-3640d7403c6f.png)

**Comment by DerekMoss95** [comment]
All departments have this calendar widget

**Comment by DerekMoss95** [comment]
I have checked most all department sites and they all have the option for the calendar. I don't know whether they have calendars but they have the option on the home page to display that calendar.
