### ISSUE TITLE
Remove emeriti faculty from the first "all" view of the directory

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#68]
From: Tessa Hauglid <tessa_hauglid@byu.edu>
Subject: Question
To: Tory Anderson <tory_anderson@byu.edu>
Date: Wed, 10 Jan 2018 18:15:09 +0000 (2 hours, 17 minutes, 55 seconds ago)
Resent-From: <tory_anderson@byu.edu>

Is it possible for us to have emeriti faculty not show up on our
directory under “all” but show up under “emeritus”?

 

Thanks.

 

_______________________

Tessa Hauglid

English Department Secretary

4198 JFSB

Brigham Young University

Provo, UT 84602

801-422-4939

tessa_hauglid@byu.edu

**Comment by DerekMoss95** [comment]
Does this mean that she wants the "Emeriti" in the directory drop down to read emeritus?

Or does it mean that she doesn't want emeriti faculty to show up when the user clicks all? 

I am a little confused by this request.

**Comment by WorldsEndless** [comment]
She means she doesn't want the users in that category to show up in the initial "all" load, the same way student instructors don't show up at first.

**Comment by DerekMoss95** [comment]
I just removed emeritus from the following line of code in the /shortcodes/register.php
`    $block.="<li class='filterable-item ".(in_array($person->acf->status,array("full","part",**"emeritus"**,"staff","visiting")) ? "" : " student ")."department-".$person->acf->department->post_title." status-".$person->acf->status."'>";
`

**Comment by aaroncowley** [comment]
changed class of hidden faculty to "hidden_faculty" instead of "student" to reflect more accurately the objects being hidden
