### ISSUE TITLE
Fix all department program requirement links

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#69]
Links must correspond to the correct catalog path. For example, for the Arabic minor, the catalog page is this:

https://catalog.byu.edu/humanities/asian-and-near-eastern-languages/arabic-minor

Therefore the link referenced in the shortcode must refer to dept=asian-and-near-eastern-languages and program=arabic-minor. 

You can verify if your path is correct by inserting those values into the micro-service url (this is what the shortcode creates behind the scenes):

http://humpre.byu.edu/scraper/requirements/asian-and-near-eastern-languages/arabic-minor

**Comment by WorldsEndless** [comment]
It looks like some of their links have been set up wrong.

**Comment by DerekMoss95** [comment]
I don't fully understand what is going on here. What is incorrect about their program requirement links? What is it that they want it to be instead exactly?

**Comment by WorldsEndless** [comment]
Example: http://ane.byu.edu/heb/hebrew/biblical-hebrew/

The shortcode is failing; it is wrongly entered as:
[requirements dept='asian-and-near-eastern-languages' program='biblical-hebrew-minor']

All such shortcodes need to be changed to:

[requirements org='asian-and-near-eastern-languages' program='biblical-hebrew-minor']

So the shortcodes need to be refactored from dept to org.

**Comment by sassteve** [comment]
The description shortcodes are faulty as well and I'm not quite sure how to fix them. The example is [descriptions title='Current IHUM classes' yt='20131' org='IHUM']. Does this connect with the course list (http://catalog.byu.edu/course-list/IHUM)?

**Comment by WorldsEndless** [comment]
Requirements seem to be working, right? 

c/o http://ane.byu.edu/heb/hebrew/biblical-hebrew/

Have these been fixed everywhere?

**Comment by sassteve** [comment]
Yes, no issues regarding the [requirements org='asian-and-near-eastern-languages' program='biblical-hebrew-minor'] shortcode. Though the course descriptions and schedules are still broken, which is a scraper issue as previous discussed.
