### ISSUE TITLE
Change file listings to not display full mime type

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#73]
>     From: "Spanish &amp; Portuguese Department" <spanport-dept@byu.edu>
>     Subject: SpanPort website question
>     Date: January 31, 2018 at 12:19:02 PM MST

![screenshot](https://user-images.githubusercontent.com/5042778/35651426-e0baf3d4-069c-11e8-8e50-56d6e8b7fcdc.png)
> My name is Camille, I am one of the student secretaries in the Spanish and Portuguese Department. I am wondering if you can help with a website issue? If not, will you please refer me to someone who can help?  At the bottom of this page, there is a link that says “Application”. Can this be removed? Some students get confused because they think this link will lead to the Masters Program application. Clicking on the “Application” link leads to the Hispanic Linguistics page.  Multiple people in the department have tried removing this through Learning Commons access, but nobody has figured it out.

>      
>     Thank you!!

**Comment by DerekMoss95** [comment]
The title of this issue and the screenshot of the request are quite different. Do we want to remove the MIME Extension or do we just want to remove the Application link?

**Comment by WorldsEndless** [comment]
They are confused by the presence of the word "Application", so 
just that word needs to be removed.

**Comment by DerekMoss95** [comment]
Commented a few things out and it is good to go.
