### ISSUE TITLE
Standardize Phone number display

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#78]
Phone numbers are often formatted differently by users, causing a variety of displays. They should have a consistent display across all the college.

**Comment by WorldsEndless** [comment]
Possible approach would be to put a filter in place on the directory pages everywhere. Logic might be:

1. Strip phone number to ONLY numbers.
2. If the count of numbers is 10, insert parenthesis before and after the first 3 digits
3. Insert a hyphen before the 4th-from-last digit

**Comment by DerekMoss95** [comment]
Finished. I changed this function:
```

    if (!empty($person->acf->phone)) {
      $block.="<div class=\"link\"><i class=\"icon byu-icon-telephone\"></i><span>".$person->acf->phone."</span></div>";
    }


```
Into this: 

```
if (!empty($person->acf->phone)) {
      $phone = $person->acf->phone;
      $phone = preg_replace('/\D/', '', $phone);
      if (strlen($phone) == 10) {
        $phone = '('.substr($phone, 0, 3).')'.substr($phone, 3, 3).'-'.substr($phone,6);
        $block.="<div class=\"link\"><i class=\"icon byu-icon-telephone\"></i><span>".$phone."</span></div>";
      }
    }
```
