### ISSUE TITLE
Plan deployment strategy

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#9]
What process needs to be followed to make our changes functional and live on all sites with no down time? 

- no echoes in the code
- Dynamic code instead of hard-coding where possible
- Plugins upgraded and configured as necessary
- Changes pushed to git

**Comment by aaroncowley** [comment]
from what ive seen in both the make list and directory list functions the only hard coding we have is just the links to the json and the status map mapping the status field to "Full-time", "Part time", etc... which im thinking will be fine and as a low chance of becoming broken anytime soon

**Comment by aaroncowley** [comment]
>acf to rest api installed
>any rest api plugin disabled so core rest api can activate
>BYUH TOOLS page needs slug of department site ie spanish-and-portuguese
>links changed from humstaging.byu.edu/humanites/wp-json/wp/v2/etc.... to humanities.byu.edu/wp-json/wp/v2/
